# Generated by Django 3.1.5 on 2021-02-25 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_object_id', models.PositiveIntegerField()),
                ('shipping_address', models.JSONField(verbose_name='Shipping address')),
                ('billing_address', models.JSONField(verbose_name='Billing address')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('owner_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'Customer')), models.Q(('app_label', 'accounts'), ('model', 'User')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PACKAGED', 'Packaged'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('UNDELIVERED', 'Undelivered'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=55, verbose_name='Status')),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('TRY', '₺')], max_length=3, verbose_name='Currency')),
                ('tax_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Price tax rate')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price including discount and tax', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit price')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('discount_rate', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount rate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('package', models.ForeignKey(blank=True, help_text='Seller can package and send packaged order lines together for shipment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='orders.package')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
            },
        ),
    ]
