# Generated by Django 3.1.5 on 2021-02-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.JSONField(verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
    ]
