# Generated by Django 3.1.5 on 2021-03-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, help_text='This is a flag that represents whether deleted. True means deleted.')),
                ('name', models.CharField(max_length=255, verbose_name='Courier name')),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='Tracking code')),
                ('tracking_url', models.URLField(max_length=255, verbose_name='Tracking url')),
                ('fee', models.CharField(max_length=255, verbose_name='Shipment fee')),
                ('is_buyer_pays', models.BooleanField(default=False, verbose_name='Is the shipment buyer pays?')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.courier')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
