# Generated by Django 3.1.5 on 2021-02-13 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Country Name')),
                ('alpha2_code', models.CharField(max_length=2, verbose_name='Alpha-2 Code')),
                ('alpha3_code', models.CharField(max_length=3, verbose_name='Alpha-3 Code')),
                ('numeric_code', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Numeric Code')),
            ],
        ),
    ]
