# Generated by Django 3.1.5 on 2021-02-13 20:01

from django.db import migrations
from django.utils.translation import gettext_lazy as _


def create_countries(apps, schema_editor):
    """
    Creates countries objects for :model:`accounts.Country`.
    """
    Country = apps.get_model("accounts", "Country")

    Country.objects.create(
        name=_("Turkey"),
        alpha2_code="TR",
        alpha3_code="TUR",
        numeric_code=792,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_countries),
    ]
