# Generated by Django 3.1.5 on 2021-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210227_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='This is a flag that represents whether deleted. True means deleted.'),
        ),
    ]
