# Generated by Django 3.1.5 on 2021-02-13 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210213_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2_code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Alpha-2 Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Alpha-3 Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='numeric_code',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Numeric Code'),
        ),
    ]
