# Generated by Django 3.1.5 on 2021-02-23 15:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210220_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contact Phone Number'),
        ),
    ]
