# Generated by Django 3.1.5 on 2021-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210201_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='This is a flag that represents whether deleted. True means deleted.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='This is a flag that represents whether deleted. True means deleted.'),
        ),
    ]
