# Generated by Django 3.1.5 on 2021-02-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210214_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date and time'),
        ),
    ]
